name: CI

on:
  push: 
    branches: 
      - main
    paths-ignore:
      - 'README.md'
      - 'k8s/**'
      - 'helm/**'

jobs:

  build:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up GO
      uses: actions/setup-go@v4
      with:
        go-version: 1.22

    - name: Build
      run: go build -o go-web-app
    
    - name: Test
      run: go test -v ./...

  code_quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.56.2

  image_build:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASS }}

    - name: Build and push image to Docker Hub
      uses: docker/build-push-action@v6.10.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-web-app:${{ github.run_id }}
        